import fire
import subprocess

class RemoveBuildTempTag(object):
  """ Remove Temp Tags generated by Unity Build """

  def build(self):
    get_tags_cmd = 'git tag -l'
    tags = subprocess.check_output(get_tags_cmd, shell=True)
    tags = tags.split('\n')

    for i in range(len(tags)):
        if 'temp-unity-build-' in tags[i]:
            rm_tag_cmd = 'git tag -d ' + tags[i] + " && git push local :"+tags[i]
            subprocess.check_output(rm_tag_cmd, shell=True)

if __name__ == '__main__':
    fire.Fire(RemoveBuildTempTag)
